# Site settings
email: axquired24@gmail.com
baseurl: "https://axquired24.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: AxQuired24 Official Share
description: Blog untuk share semua yang terfikirkan 
url: "https://axquired24.github.io"
twitter_username: axquired24
default_img: 

# Profile settings
name: Albert Septiawan
profile_img: 
profile: 
social:
  github: "https://axquired24.github.io"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
